nguyenlp04/DATN-GoodAndCheap-OneDream

app/Http/Controllers/CategoryController.php

fix sql category

---

resources/views/admin/notifications/create_notifications.blade.php
resources/views/admin/notifications/list_notifications.blade.php
resources/views/admin/notifications/trashed_notifications.blade.php
routes/web.php

update layout notifi

---

app/Http/Controllers/ProductController.php

update json data product

---

app/Http/Controllers/NotificationController.php
app/Models/Notification.php
resources/views/admin/notifications/create_notifications.blade.php
resources/views/admin/notifications/edit_notifications.blade.php
resources/views/admin/notifications/list_notifications.blade.php
routes/web.php

Partner management - layout notifi

Partner management

---

public/assets/css/style.css
resources/views/account/partials/account_edit.blade.php
resources/views/account/partials/update-password.blade.php
resources/views/blocks/client/header.blade.php

user_followed

---

app/Http/Controllers/ChannelController.php

fix view channel by id

---

app/Http/Controllers/SaleNewsController.php
app/Http/Controllers/VnPayController.php
resources/views/blocks/client/header.blade.php
resources/views/layouts/partner_layout.blade.php
resources/views/salenews/index.blade.php
resources/views/salenews/search.blade.php

fix giao dien

---

resources/views/layouts/partner_layout.blade.php

update edit info

---

app/Console/Commands/CheckVipStatus.php
app/Http/Controllers/VnPayController.php
composer.lock
resources/views/admin/categories/update-category.blade.php

send mail payment

---

app/Http/Controllers/SaleNewsController.php
app/Providers/AppServiceProvider.php
resources/views/blocks/client/header.blade.php
resources/views/partner/sale_news/add.blade.php
resources/views/salenews/add-sale-news.blade.php
resources/views/salenews/search.blade.php
routes/web.php

feature search

---

resources/views/layouts/client_layout.blade.php
resources/views/salenews/search.blade.php

add filter price sale news

---

app/Http/Controllers/SaleNewsController.php
app/Http/Controllers/VnPayController.php
app/Services/PhpMailerService.php
public/admin/js/notification.json
public/assets/js/main.js
resources/views/admin/config/vnpay.blade.php
resources/views/blocks/client/header.blade.php
resources/views/layouts/admin.blade.php
resources/views/salenews/search.blade.php

fix send mail env

---

app/Http/Controllers/SaleNewsController.php
resources/views/blocks/client/header.blade.php
resources/views/salenews/search.blade.php

fix search price

---

app/Http/Controllers/SaleNewsController.php

Fix search search price

---

app/Http/Controllers/SaleNewsController.php

filter-price

---

app/Http/Controllers/SaleNewsController.php

fix dlt search

---

resources/views/layouts/client_layout.blade.php
resources/views/salenews/search.blade.php

Filer price

---

public/assets/js/main.js
resources/views/partials/main.blade.php

sale newss

---

app/Http/Controllers/BlogController.php
resources/views/blog/listting.blade.php
resources/views/layouts/client_layout.blade.php
resources/views/salenews/search.blade.php

sale_newsss

---

app/Http/Controllers/WishlistController.php
resources/views/layouts/wishlist.blade.php

sale new channel

---

resources/views/blocks/client/footer.blade.php

search mobile

---

app/Http/Controllers/DashboardController.php
public/admin/assets/js/dashboards-analytics.js
resources/views/admin/index.blade.php

Weekly Revenue Chart
